build: false
shallow_clone: true

environment:
  CHOCO_COMPOSER_VERSION: 5.0.0.20191205

install:
  - cinst php -i -y
  #- cinst composer  -y --version %CHOCO_COMPOSER_VERSION%
  - cinst composer -i -y --version %CHOCO_COMPOSER_VERSION% --source %APPVEYOR_BUILD_FOLDER%

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - refreshenv
  - php -v
  - composer --version --ansi
  - echo Composer Setup %CHOCO_COMPOSER_VERSION% successfully installed
