build: false
shallow_clone: true

environment:
  CHOCO_COMPOSER_VERSION: 4.8.0

install:
  - cinst php -i -y
  - cinst composer -i -y --version %CHOCO_COMPOSER_VERSION%

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - refreshenv
  - composer --version --ansi
  - echo Composer Setup %CHOCO_COMPOSER_VERSION% successfully installed
