build: false
shallow_clone: true

environment:
  CHOCO_COMPOSER_VERSION: 4.10.0

install:
  - cinst php -y --force --params "/InstallDir:c:\tools\php"
  - refreshenv
  #- cinst composer  -y --version %CHOCO_COMPOSER_VERSION%

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - where php
  - php -v
  - echo Testing install
  - cinst composer -i -y --source %APPVEYOR_BUILD_FOLDER%
  - refreshenv
  - where composer
  - composer --version --ansi
  - echo Testing uninstall
  - choco uninstall -y composer
