build: false
shallow_clone: true

environment:
  CHOCO_COMPOSER_VERSION: 4.10.0

install:
  - cinst php -i -y --force --version 7.3.11 --params "/InstallDir:c:\tools\php"
  - refreshenv
  #- cinst composer  -y --version %CHOCO_COMPOSER_VERSION%

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - php -v
  - echo Testing install
  - cinst composer -i -y --source %APPVEYOR_BUILD_FOLDER%
  - refreshenv
  - composer --version --ansi
  - echo Testing uninstall
  - choco uninstall -y composer
