# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: 'windows-latest'

steps:

- script: php -v
  displayName: PHP Version

- bash: |
    choco install -y php --version 7.4.0 --no-progress
    echo "##vso[task.setvariable variable=php]$(which php)"
  displayName: 'Install PHP 7.4.0'

- bash: |
    choco install -y composer --no-progress
    echo "##vso[task.setvariable variable=composer]$(which composer)"
  displayName: Install composer

- bash: |
    $(php) -v
    $(composer) --version
  displayName: Display versions
